---
title: "Transfer from rds to h5ad"
author: "Wenqing Chen"
date: "2025-05-05"
output: html_document
---

```{r setup, include=FALSE}

#install.packages("remotes")
#remotes::install_github("mojaveazure/seurat-disk")

library(Seurat)
library(SeuratDisk)
library(SeuratObject)


```



```{r}

rds_data <- readRDS("/Users/wenqchen/Desktop/Projects/Auria/Data/scRNA/TNBC180225.rds")
rds_data <- readRDS("/Users/wenqchen/Desktop/Projects/Auria/Data/scRNA/TNBC_signatures.rds")
class(rds_data)

rds_data@reductions <- list()

# 把 meta.data 中的 factor 类型转换成字符
rds_data@meta.data[] <- lapply(rds_data@meta.data, function(x) {
  if (is.factor(x)) as.character(x) else x
})

SaveH5Seurat(rds_data, filename = "TNBC180225.h5Seurat", overwrite = TRUE)
Convert("TNBC180225.h5Seurat", dest = "h5ad", overwrite = TRUE)


#----------------------------------------------------------------------------------

# get the count dataframe
write.csv(as.matrix(rds_data@assays$RNA$counts), file = "/Users/wenqchen/Desktop/Projects/Auria/Data/scRNA/TNBC_counts.csv")
# get metadata file
write.csv(rds_data@meta.data, file = "/Users/wenqchen/Desktop/Projects/Auria/Data/scRNA/TNBC_metadata.csv")


```



